nelmio_api_doc:
  documentation:
    info:
      title: Secret Server
      description: This is an API of a secret service. You can save your secret by using the API. You can restrict the access of a secret after the certen number of views or after a certen period of time.
      version: 1.0.0
#  areas: # to filter documented areas
#    path_patterns:
#      - ^/api(?!/doc$) # Accepts routes under /api except /api/doc